name: Build & publish front docker images

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Calcuate version
      run: echo "VERSION=$(date +'%Y.%m.%d').${{github.run_number}}" >> $GITHUB_ENV
    - name: debug
      run: echo VERSION = $VERSION 
    - name: Login dockerhub
      run: docker login -u cryptolynx --password ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build server image
      run: docker build -f Dockerfile-front -t cryptolynx/captain-bridge-front:$VERSION .
    - name: Push server image
      run: docker push cryptolynx/captain-bridge-front:$VERSION
