name: Release tag as latest.

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: debug
      run: echo VERSION = ${{ github.event.inputs.tag }} 
    - name: Login dockerhub
      run: docker login -u cryptolynx --password ${{ secrets.DOCKERHUB_TOKEN }}
